__title__ = "Pururu"
__description__ = "Discord bot for managing attendance."
__url__ = "https://github.com/jlvadell/pururu-bot"
__version__ = "1.1.0"
__author__ = "Jose Vadell"
__author_email__ = "me@jlvadell.com"
__license__ = "Apache-2.0"
__copyright__ = "Copyright Jose Vadell"
