name: Deploy EC2
on:
  push:
    tags:
      - 'v*'
  pull_request: #just for testing remove after
    types: [ opened, synchronize, reopened ] #just for testing remove after
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get Configuration building script
      uses: actions/checkout@v4
      with:
          repository: jlvadell/general-scripts
          path: general-scripts
          ssh-key: ${{ secrets.SCRIPTS_REPO_SSH_PRIVATE }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Run build_pururu_secrets.py script
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        GS_ATTENDANCE_PLAYER_MAPPING: ${{ secrets.GS_ATTENDANCE_PLAYER_MAPPING }}
        GUILD_ID: ${{ secrets.GUILD_ID }}
        PLAYERS: ${{ secrets.PLAYERS }}
        SPREADSHEET_CREDS: ${{ secrets.SPREADSHEET_CREDS }}
      run: | 
        python general-scripts/create_secrets_file/build_pururu_secrets.py > /dev/null 2>&1
      working-directory: .

    - name: Clean project folder
      run: |
        rm -rf ./general-scripts

    - name: Load EC2 Key
      run: |
        echo "${{ secrets.EC2_KEY }}" | base64 -d > /tmp/ssh_key
        chmod 600 /tmp/ssh_key

    - name: Copy project files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i /tmp/ssh_key -r ./* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/app/

    - name: Deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/${{ secrets.EC2_USER }}/app/
          docker build -t pururu-bot .
          docker stop pururu-bot || true
          docker rm pururu-bot || true
          docker run -d --name pururu-bot pururu-bot
        EOF